### ISSUE TITLE
No module named 'Crypto'

### ISSUE THREAD

**Issue by 89z** [opengapps/apkcrawler#76]
PS D:\Desktop\apkcrawler-master> 'com.google.android.youtube' | python.exe .\playstorecrawler.py
Traceback (most recent call last):
  File "D:\Desktop\apkcrawler-master\playstorecrawler.py", line 14, in <module>
    from googleplayapi.googleplay import GooglePlayAPI
  File "D:\Desktop\apkcrawler-master\googleplayapi\googleplay.py", line 13, in <module>
    from Crypto.PublicKey import RSA
ModuleNotFoundError: No module named 'Crypto'

**Comment by tenzap** [comment]
I face the same issue.

Replace "Crypto" by "Cryptodome" and be sure to have cryptodome module installed
